[package]
name = "mycitadel-desktop"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "MyCitadelDesktop"
path = "src/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gtk = { version = "0.4.7", package = "gtk4" }
relm4 = "0.4.4"
relm4-macros = "0.4.4"
relm4-components = "0.4.4"
gladis = "2.0.0"
