[package]
name = "mycitadel-desktop"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "mycitadel"
path = "src/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gtk = "0.15.4"
relm = "0.23.0"
relm-derive = "0.23.0"
gladis = "2.0.0"
once_cell = "1.10.0"
chrono = "0.4.19"

amplify = "3.12.0"
bitcoin = "0.28.0-rc.2"
miniscript = "7.0.0-rc.2"
hwi = "0.1.3"
electrum-client = "0.10.0-rc.2"
descriptor-wallet = { version = "0.7.0-beta.2", features = ["miniscript", "keygen"] }
strict_encoding = "1.8.0-rc.9"

[patch.crates-io]
bitcoin = { git = "https://github.com/rust-bitcoin/rust-bitcoin" }
miniscript = { git = "https://github.com/LNP-BP/rust-miniscript", branch = "canary" }
strict_encoding = { version = ">=1.8.0-rc.10", git = "https://github.com/LNP-BP/client_side_validation", branch = "sten/bitcoin-fixes" }
descriptor-wallet = { git = "https://github.com/LNP-BP/descriptor-wallet" }
