[package]
name = "mycitadel-desktop"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "MyCitadelDesktop"
path = "src/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gtk = "0.15.4"
relm = "0.23.0"
relm-derive = "0.23.0"
gladis = "2.0.0"
